--- #YAML:1.0
name:                Clutter
version:             1.002
abstract:            Simple GL-based canvas library
license:             perl, lgpl
author:              
    - Emmanuele Bassi <ebassi@linux.intel.com>
generated_by:        ExtUtils::MakeMaker version 6.44
distribution_type:   module
requires:     
    Cairo:                         1.000
    ExtUtils::Depends:             0.300
    ExtUtils::PkgConfig:           1.030
    Glib:                          1.220
    Pango:                         1.140
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
