---
abstract: 'Perl interface to the 1.x series of the Clutter toolkit'
author:
  - 'Emmanuele Bassi <ebassi@gnome.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300015, CPAN::Meta::Converter version 2.120921'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Clutter
requires:
  Cairo::GObject: 1.000
  Glib: 1.253
  Glib::Object::Introspection: 0.002
  Pango: 1.220
version: 1.110
